name = "lean-playground"
version = "0.1.0"
defaultTargets = ["lean-playground"]

[[lean_lib]]
name = "LeanPlayground"

[[lean_exe]]
name = "lean-playground"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"